version: '3.8'

services:
  # Servicio de la aplicación NestJS
  app:
    image: ${{ secrets.DOCKER_USERNAME }}/my-app:latest # Usa la imagen publicada en Docker Hub
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expone el puerto 3000 de la aplicación
    environment:
      - MONGODB_URI=mongodb://mongo:27017/FourBros # Conexión a MongoDB
    depends_on:
      - mongo # Asegura que MongoDB esté disponible antes de iniciar la aplicación

  # Servicio de MongoDB
  mongo:
    image: mongo:6.0 # Versión de MongoDB
    container_name: mongo-db
    ports:
      - "27017:27017" # Expone el puerto de MongoDB
    volumes:
      - mongo-data:/data/db # Persiste los datos de MongoDB

volumes:
  mongo-data: # Volumen para almacenar los datos de MongoDB